### ISSUE TITLE
AudioWorklet or MediaStreamTrackProcessor can be substituted for decodeAudioData

### ISSUE THREAD

**Issue by guest271314** [johncalvinroberts/pprmnt#166]
> Performance -- current state is not optimized for speed, I just wanted to get this thing working. There are lots of areas for improvement. Currently, the slowest operation is `BaseAudioContext.decodeAudioData()`.

`AudioWorklet` or `MediaStreamTrackProcessor` can be substituted for `decodeAudioData` https://plnkr.co/edit/s0TBFFoj1Vs2yGu7?preview.

**Comment by guest271314** [comment]
@johncalvinroberts I updated the linked plnk. I don't think we need WASM to encode PCM to MP3.

**Comment by johncalvinroberts** [comment]
@guest271314 I checked the plnk you linked. It seems ultimately the underlying implementation depends on `lamejs`, a JS port of `lame` -- the original C library that we're using in `pprmnt`. 

Yeah, sure we don't **need** WASM to encode to MP3 in the browser. But the WASM version of the C lib **should** be faster and use less memory than the JS backport. Would love to see a benchmark of that 😉 

Do you have any insight there? i.e., `lamejs` vs. `emscripten` build of original `lame` @guest271314

**Comment by guest271314** [comment]
My use case is calling the script at `console` or on Chromium from Sources -> Snippets. To call WASM CORS headers are required, which means I need to create an extension (see https://github.com/guest271314/captureSystemAudio#web-accessible-resources-php-passthru-parec-fetch-transferable-streams-media-capture-transform-breakout-box, https://github.com/guest271314/captureSystemAudio/blob/master/native_messaging/capture_system_audio/transferableStream.js) to bypass CSP restrictions by utilizing `"web_accessible_resources"` (`AudioWorklet` as Ecmascript module has same restriction https://github.com/WebAudio/web-audio-api-v2/issues/109). Thus, for my use case I would prefer to have all of the code in one script that I can call directly. I have not performed any performance tests.

**Comment by guest271314** [comment]
@johncalvinroberts Basically, if I am on, e.g., soundcloud or youtube and want to capture the sounds I hear, and  compress PCM to MP#, or any other codec, if `fetch()` is involved I will get CSP errors if I do not use a workaround.

**Comment by johncalvinroberts** [comment]
Okay got it. In other words, you're working on a browser extension, and can't use WASM bundles due to cross origin restrictions. Am I understanding that correctly? @guest271314

**Comment by guest271314** [comment]
I already built the browser extension, I linked to one of several versions. I am just coveying to you the restrictions face in such use cases when `fetch()` and WebAssembly methods are used at `console` (when you are not on a domain you control and CSP is involve).

**Comment by johncalvinroberts** [comment]
Okay awesome. Thank you so much for sharing!! I guess this isn't really relevant to `pprmnt` anymore, since it doesn't actually have any network activity related to the use of WASM. So I'm gonna close the issue

Please feel free to share anything else that you learn about audio encoding in the browser in the future :)
