### ISSUE TITLE
Batch download of all files

### ISSUE THREAD

**Issue by cowchimp** [johncalvinroberts/pprmnt#98]
Thanks for this very handy tool!

Would appreciate a button to download all files after doing a batch conversion, rather than needing to download each file individually.

**Comment by johncalvinroberts** [comment]
Hi @cowchimp --

Firstly, sorry about the extremely long delay for getting your little feature request addressed. My apologies.

Secondly, I added a quick implementation. Do you have any feedback? 
* Implementation is in #167 
* Preview here: [link](https://deploy-preview-167--musing-yalow-be7560.netlify.app/)

**Comment by cowchimp** [comment]
Works like a charm! Thank you very much 🙏
